package com.seiken_soft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.seiken_soft.entity.TDuty;
import com.seiken_soft.entity.TDutyExample;
import com.seiken_soft.entity.TDutyKey;

@Mapper
public interface TDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    long countByExample(TDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int deleteByExample(TDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int deleteByPrimaryKey(TDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int insert(TDuty tDuty);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int insertSelective(TDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    List<TDuty> selectByExample(TDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    TDuty selectByPrimaryKey(TDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("record") TDuty record, @Param("example") TDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int updateByExample(@Param("record") TDuty record, @Param("example") TDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(TDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_duty
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    int updateByPrimaryKey(TDuty record);
}