package com.seiken_soft.entity;

public class MEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_employee.EMPLOYEE_NAME
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_employee.E_MAILADDRESS
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    private String eMailaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_employee.EMPLOYEE_ID
     *
     * @return the value of m_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_employee.EMPLOYEE_ID
     *
     * @param employeeId the value for m_employee.EMPLOYEE_ID
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_employee.EMPLOYEE_NAME
     *
     * @return the value of m_employee.EMPLOYEE_NAME
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_employee.EMPLOYEE_NAME
     *
     * @param employeeName the value for m_employee.EMPLOYEE_NAME
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_employee.E_MAILADDRESS
     *
     * @return the value of m_employee.E_MAILADDRESS
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public String geteMailaddress() {
        return eMailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_employee.E_MAILADDRESS
     *
     * @param eMailaddress the value for m_employee.E_MAILADDRESS
     *
     * @mbg.generated Wed Jun 18 21:02:50 GMT+09:00 2025
     */
    public void seteMailaddress(String eMailaddress) {
        this.eMailaddress = eMailaddress == null ? null : eMailaddress.trim();
    }
}